services:
  logs-server-app:
    image: ${DOCKER_USERNAME}/${DOCKER_SERVER_APP_NAME}:latest
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    networks:
      - logs-network
    
  logs-client-app:
    image: ${DOCKER_USERNAME}/${DOCKER_CLIENT_APP_NAME}:latest
    ports:
      - "${CLIENT_PORT}:3000"
    env_file:
      - .env

networks:
  logs-network:
    driver: bridge