services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - logs-network

  logs-server-app:
    image: ${DOCKER_USERNAME}/${DOCKER_SERVER_APP_NAME}:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - logs-network
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/logs

  logs-client-app:
    image: ${DOCKER_USERNAME}/${DOCKER_CLIENT_APP_NAME}:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - logs-network
    depends_on:
      - logs-server-app

networks:
  logs-network:
    driver: bridge

volumes:
  mongodb_data:
