services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - logs-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: ${DOCKER_SERVER_APP_NAME:-logs-server}
    ports:
      - 8080:8080
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/logs
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - logs-network
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:${SERVER_PORT:-8080}/api/v1/health",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: ${DOCKER_CLIENT_APP_NAME:-logs-frontend}
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    depends_on:
      - backend
    networks:
      - logs-network

networks:
  logs-network:
    driver: bridge

volumes:
  mongodb_data:
